name: Component Detection

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

permissions:
  contents: write
  id-token: write

jobs:
  dependency-submission:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025, ubuntu-22.04, ubuntu-24.04]      
    runs-on: ${{ matrix.os }}
    name: Component Detection (${{ matrix.os }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
          # dotnet-version: '9.0.x'
          # dotnet-quality: 'preview'

      - name: Ensure .NET MAUI workload is installed
        shell: pwsh
        run: |
          if (-not (dotnet workload list | Select-String "maui-android")) {
            dotnet workload install maui
          }

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Component Detection
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
        with:
          filePath: '.'
